Meteor.organizations = {
  linkedin : {link: "https://business.linkedin.com/talent-solutions/recruiter", style:"background-image: url(organizations/linkedin.png); background-color:white; background-size: 105%; background-repeat:no-repeat", name: "LinkedIn", position: "Software Engineer", role: "Search ranking relevance models and API services."},
  icspi : {link: "http://icspicorp.com", style:"background-image: url(organizations/icspi.jpg); background-color:white; background-size: 80%; background-repeat:no-repeat", name: "ICSPI Nano Robotics", position: "Mechatronics Engineer", role: "Digital signal processing, electrical design, desktop GUI."},
	voltera : {link: "http://voltera.io/", style:"background-image: url(organizations/voltera.jpg); background-color:white; background-size: 80%; background-repeat:no-repeat", name: "Voltera", position: "Software Developer", role: "PCB printer motion planning algorithms and UI/UX design."},
	deca : {link: "http://deca.ca", style:"background-image: url(organizations/deca.png); background-size: 110%;", name: "DECA Ontario", position: "International Winner", role: "Consulted for Alterna Savings in online strategy case competition."},
	bitmaker : {link: "http://www.bitmakerlabs.com", style:"background-image: url('organizations/bitmaker2.png'); background-size: 100%;", name: "Bitmaker Labs", position: "Alumnus", role: "Immersive web development bootcamp in Toronto."},
	mytf : {link: "http://www.markhamyouth.com", style:"background-image: url('organizations/mmyc.png'); background-size: 90%;", name: "Markham Mayor's Council", position: "Director", role: "Reached 20,000 youth through holding 20 large-scale events."},
	glowstik : {link: "http://www.glowstik.ca", style:"background-image: url(organizations/glowstik.png); background-size: 100%;", name: "Glowstik Social Marketing", position:"Head of Strategy", role:"A social media marketing consultancy in Toronto."},
	phasma : {link: "http://phasmaband.bandcamp.com/", style:"background-image: url('organizations/phasma.jpg'); background-size: 100%;", name: "Phasma", position:"Studio and Live Percussionist", role:"A punk rock band I co-founded. Recorded 4 studio EPs."},
	soccer : {link: "http://www.u-msc.com/Default.asp?id=home&l=1", style:"background-image: url('organizations/umsc.png'); background-size: 85%; background-repeat:no-repeat", name: "UM Soccer Club", position:"Defenseman", role:"Played defense at the Unionville-Milliken Soccer Club."},
	top_scholar : {link: "http://www.yrdsb.edu.on.ca/pdfs/w/news/NW1407081.pdf", style:"background-image: url(https://pbs.twimg.com/profile_images/494835763326885889/MOygWXwZ.png); background-size: 95%;", name: "York School Board", position:"Top Scholar", role:"Achieved 3rd highest graduating average out of 115,000 students."},
	ccs : {link: "https://www.youtube.com/watch?v=HAlkA579Lp4", style:"background-image: url(http://www.cancer.ca/img/CCSSite/ccs_logo_fb.png); background-size: 100%; background-repeat: no-repeat", name: "Canadian Cancer Society", position:"Youth Council President", role:"Coordinated $10,000 in donations across York Region."},
};
